services:
  evently.api:
    image: evently.api
    depends_on:
      evently.db:
        condition: service_healthy
    build:
      context: .
      dockerfile: src/Api/Evently.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5001:8080"
  
  evently.db:
    image: postgres
    healthcheck:
      test: pg_isready -U postgres -d evently
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      - POSTGRES_DB=evently
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MyPass123
    volumes:
      - ./postgres-data/:/var/lib/postgresql/
    ports:
       - "54320:5432"
  
  evently.seq:
    image: datalust/seq:2025.2
    environment:
      - ACCEPT_EULA=y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=True
    ports:
      - "5341:5341"
      - "8081:80"
  
  evently.redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"