services:
  evently.api:
    image: evently.api
    depends_on:
      evently.db:
        condition: service_healthy
    build:
      context: .
      dockerfile: src/Api/Evently.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5001:8080"
  evently.db:
    image: postgres
    healthcheck:
      test: pg_isready -U postgres -d evently
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      - POSTGRES_DB=evently
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MyPass123
    volumes:
      - ./postgres-data/:/var/lib/postgresql/
    ports:
       - "54320:5432"

